### ISSUE TITLE
in grosse room crasha brutto

### ISSUE THREAD

**Issue by blackout314** [dlion/smagenBot#2]
TypeError: Cannot call method 'charAt' of undefined  
    at smagenBot.makeAction (/home/blackout/GIT/smagenBot/bin/smagenBot.js:39:11)  
    at /home/blackout/GIT/smagenBot/index.js:17:17  
    at Request._callback (/home/blackout/GIT/smagenBot/bin/smagenBot.js:21:9)  
    at Request.self.callback (/home/blackout/GIT/smagenBot/node_modules/request/request.js:197:22)  
    at Request.emit (events.js:98:17)  
    at Request.<anonymous> (/home/blackout/GIT/smagenBot/node_modules/request/request.js:1050:14)  
    at Request.emit (events.js:117:20)  
    at IncomingMessage.<anonymous> (/home/blackout/GIT/smagenBot/node_modules/request/request.js:996:12)  
    at IncomingMessage.emit (events.js:117:20)  
    at _stream_readable.js:944:16

**Comment by blackout314** [comment]
smagenBot -> riga 39
sostituire con

if(typeof text !== "undefined" && text.charAt(0) === '/') {

come check di ulteriore sicurezza (all'avvio) perche capita che text sia undefined

**Comment by dlion** [comment]
È che non l'ho ancora testato sui gruppi ma solo su conversazioni private, con la tua modifica si fixa o il bug rimane ?

**Comment by blackout314** [comment]
fix che va alla grande :smile:

**Comment by dlion** [comment]
Ottimo, faccio il merge!

**Comment by dlion** [comment]
Fixed #1
